### ISSUE TITLE
Error webhook GitLab

### ISSUE THREAD

**Issue by valentineus** [Commit451/skyhook#112]
Hello!
Thank you for the wonderful project!

I'm trying to add a GitLab hook for system events in the admin panel.
During tests, I get the following error:

```
Skyhook Error
An error has occured on skyhook for your webhook with provider gitlab. Maybe you can copy/paste or screenshot this error if there is no sensitive information and open an issue on the skyhook GitHub.

Error: "TypeError: Cannot read property 'forEach' of undefined\n at GitLab.<anonymous> (/app/dist/provider/GitLab.js:44:29)\n at Generator.next (<anonymous>)\n at /app/dist/provider/GitLab.js:6:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/GitLab.js:2:12)\n at GitLab.push (/app/dist/provider/GitLab.js:38:16)\n at GitLab.<anonymous> (/app/dist/provider/BaseProvider.js:57:33)\n at Generator.next (<anonymous>)\n at fulfilled (/app/dist/provider/BaseProvider.js:3:58)\n at process._tickCallback (internal/process/next_tick.js:68:7)"
```

## GitLab

* GitLab 11.3.6-ee (8d9cf17)
* GitLab Shell 8.3.3
* GitLab Workhorse v6.1.0
* GitLab API v4
* Ruby 2.4.4p296
* Rails 4.2.10
* postgresql

![default](https://user-images.githubusercontent.com/2735807/50046134-9d532d80-00b7-11e9-81eb-15f75229021e.png)

**Comment by dscalzi** [comment]
Do you remember what triggered this? What did you do on gitlab?

**Comment by dscalzi** [comment]
Actually, I see the issue here. You're registering a [System Hook](https://docs.gitlab.com/ee/system_hooks/system_hooks.html), which is currently not supported.

You need to register a [webhook](https://docs.gitlab.com/ee/user/project/integrations/webhooks.html) with the specific project. You can do so under the project's settings. 
**Settings > Integrations > Webhooks**.
