### ISSUE TITLE
Jira integration Skyhook error

### ISSUE THREAD

**Issue by Ixynas** [Commit451/skyhook#159]
![image](https://user-images.githubusercontent.com/22997883/95021839-2916bf00-067c-11eb-88a5-5640df552b70.png)
Hello!

Received this error, I am pretty sure this is because of anonymous person submitting a bug, so it cannot parse the field properly, since there's no reporter. Regular users passes it through, but anonymous inputs are no go. Otherwise I cannot say what else can trigger this.

Error started happening after this. Thank you for the amazing service though! <3

**Comment by aabanaag** [comment]
I just encountered this and I have no clue what caused this.

**Comment by aabanaag** [comment]
On my end, this happened because I have a trigger in my workflow that moves the ticket from TODO to In-Progress when a new branch using the ticket name is created but instead of doing it on a terminal, the branch creation was done via Jira. From what I've read so far branch creation can be done anonymously.

**Comment by dscalzi** [comment]
The jira provider only supports issue and comment actions. If you disable those triggers, does this still happen?
