### ISSUE TITLE
https://skyhook.glitch.me/ timeout

### ISSUE THREAD

**Issue by xergio** [Commit451/skyhook#55]
Hi. Bitbucket is reporting timeouts when they are pushing commits over your gateway. Is everything ok? Should I install my own gateway instead? Thank you.

**Comment by Jawnnypoo** [comment]
@dscalzi I think what is happening as far as I can tell is that if skyhook encounters an uncaught exception, it stops running, and then we start getting the 504 gateway errors, presumably because Glitch.com is attempting to direct traffic our way, and the server has ceased running, so it is 504ing. Do you know if there is a good solution to this? Presumably we could try to eliminate all errors, but it could happen for a number of reasons, and it would be hard to catch everything. Any ideas?

**Comment by dscalzi** [comment]
Hmm, 19de4cacec506c2358b97bb79559621745880467 should have fixed this issue for provider issues as they are caught and the program should continue as normal. Is the specific issue originating from a provider or from the server.js?

It's unlikely that catching an issue halts the program, but I'll check out that possibility anyway.

**Comment by Jawnnypoo** [comment]
https://github.com/Commit451/skyhook/issues/57 seems to be missing that try/catch, since it is having errors in the body parsing itself. I am not entirely sure that that is the issue causing the site to become unresponsive though. It could also be that we are attempting to parse a webhook and suspending things and never returning, or something more along those lines. Maybe we can add some timeouts on parsing the payloads in case that is what is happening?

**Comment by dscalzi** [comment]
That could be the case, does it seem like there's an infinite loop somewhere halting everything?

**Comment by Jawnnypoo** [comment]
Well, we are calling `await` here https://github.com/Commit451/skyhook/blob/master/server.js#L82
which could have the chance of getting stuck somewhere. Not sure if that would cause the server to become unresponsive though, because I think node is built in a way where it would just continue to service requests. 

Nonetheless, I am going to add an uptime monitor to the site so that I can restart it if it goes down as a temporary solution.

**Comment by dscalzi** [comment]
It's probably also best to log out what provider + function is being called each time we get a request for the next week or so at least. This is just so that we can see what was sent immediately before it crashed. With no logging we are largely in the dark.

**Comment by Jawnnypoo** [comment]
Agreed 👍 Going to close this out then while we monitor, since the site is back
